# Generated by Django 4.0.2 on 2022-03-02 04:01

import chip8.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chip8GameModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', chip8.models.fields.Chip8FileField(upload_to='games')),
            ],
        ),
    ]
