# Generated by Django 4.0.2 on 2022-03-08 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chip8', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chip8gamemodel',
            name='author',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='chip8gamemodel',
            name='description',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='chip8gamemodel',
            name='title',
            field=models.CharField(default='Please add a title.', max_length=500),
        ),
    ]
