# Generated by Django 4.0.2 on 2022-03-08 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chip8', '0002_chip8gamemodel_author_chip8gamemodel_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chip8gamemodel',
            name='author',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='chip8gamemodel',
            name='description',
            field=models.TextField(max_length=2000, null=True),
        ),
    ]
