# Generated by Django 4.0.2 on 2022-03-08 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chip8', '0003_alter_chip8gamemodel_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chip8gamemodel',
            name='author',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='chip8gamemodel',
            name='title',
            field=models.CharField(default='Please add a title.', max_length=100),
        ),
    ]
