# Generated by Django 4.0.2 on 2022-03-10 02:51

import chip8.models.fields
import chip8.models.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chip8', '0005_alter_chip8gamemodel_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chip8gamemodel',
            options={'verbose_name': 'Chip 8 Game', 'verbose_name_plural': 'Chip 8 Games'},
        ),
        migrations.AlterField(
            model_name='chip8gamemodel',
            name='file',
            field=chip8.models.fields.Chip8FileField(upload_to='games', validators=[chip8.models.validators.MaxFilesizeValidator(4096)]),
        ),
        migrations.CreateModel(
            name='KeyConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chip8_key', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(15)], verbose_name='Chip 8 Key')),
                ('keyboard_code', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^[A-Z][A-Za-z]*[0-9]?$')], verbose_name='Javascript Keyboard Code')),
                ('game_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keys', to='chip8.chip8gamemodel')),
            ],
            options={
                'verbose_name': 'Key Configuration',
                'verbose_name_plural': 'Key Configuration',
            },
        ),
        migrations.AddConstraint(
            model_name='keyconfig',
            constraint=models.UniqueConstraint(fields=('game_id', 'keyboard_code'), name='unique_keyboard_key'),
        ),
    ]
