# Generated by Django 4.0.2 on 2022-03-10 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chip8', '0006_alter_chip8gamemodel_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='KeyConfig',
            new_name='KeyConfigModel',
        ),
    ]
