# Generated by Django 4.0.2 on 2022-03-10 04:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chip8', '0007_rename_keyconfig_keyconfigmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyconfigmodel',
            name='keyboard_code',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^[A-Z][A-Za-z]*[0-9]{0,2}$')], verbose_name='Javascript Keyboard Code'),
        ),
    ]
