# Generated by Django 4.0.2 on 2022-03-15 04:19

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chip8', '0008_alter_keyconfigmodel_keyboard_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='ButtonConfigModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chip8_key', models.PositiveBigIntegerField(validators=[django.core.validators.MaxValueValidator(15)], verbose_name='Chip 8 Key')),
                ('button_id', models.CharField(choices=[('dir_left', 'D Pad - Left'), ('dir_right', 'D Pad - Right'), ('dir_down', 'D Pad - Down'), ('dir_up', 'D Pad - Up'), ('button_a', 'A Button'), ('button_b', 'B Button'), ('button_c', 'C Button'), ('button_x', 'X Button'), ('button_y', 'Y Button'), ('button_z', 'Z Button')], default='dir_left', max_length=10, verbose_name='Button Id')),
                ('game_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buttons', to='chip8.chip8gamemodel')),
            ],
            options={
                'verbose_name': 'Button Configuration',
                'verbose_name_plural': 'Button Configuration',
            },
        ),
        migrations.AddConstraint(
            model_name='buttonconfigmodel',
            constraint=models.UniqueConstraint(fields=('game_id', 'button_id'), name='unique_button_key'),
        ),
    ]
