# Generated by Django 4.0.2 on 2022-03-15 04:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chip8', '0009_buttonconfigmodel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buttonconfigmodel',
            name='chip8_key',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(15)], verbose_name='Chip 8 Key'),
        ),
    ]
